const countriesEurope = [
  "Åland",
  "Albanien",
  "Andorra",
  "Armenien",
  "Österrike",
  "Azerbajdzjan",
  "Belarus",
  "Belgien",
  "Bosnien och Hercegovina",
  "Bulgarien",
  "Danmark",
  "Estland",
  "England",
  "Finland",
  "Frankrike",
  "Island",
  "Georgien",
  "Kroatien",
  "Tyskland",
  "Grekland",
  "Ungern",
  "Irland",
  "Italien",
  "Kazakstan",
  "Lettland",
  "Liechtenstein",
  "Litauen",
  "Luxemburg",
  "Makedonien, fd jugoslaviska republiken",
  "Malta",
  "Moldova, Republiken",
  "Monaco",
  "Montenegro",
  "Norge",
  "Nederländerna",
  "Polen",
  "Portugal",
  "Rumänien",
  "Ryssland",
  "San Marino",
  "Skottland",
  "Serbien",
  "Slovakien",
  "Slovenien",
  "Sverige",
  "Spanien",
  "Schweiz",
  "Kalkon",
  "Ukraina",
  //"GBR",
  "Heliga stolen (Vatikanstaten)",
  "Wales",
];

export default countriesEurope;
